g

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,31 +20,22 @@ jobs:
           #find ${{ github.workspace }}/*/migrations -name '*.sql' -exec sqlfluff lint {} --dialect mysql --format=human \; >> lintReport.txt
           find  ${{ github.workspace }}/*/migrations -name 'V*.sql' -exec sqlfluff lint {} --dialect mysql --format=human \; | grep "==" | awk '{ print $2" "$3 }' | sed 's/\[//g' | sed 's/\]//g' > lintReport.txt
           
-  check-lint:
-    needs: lint
-    runs-on: self-hosted
-    steps:
-      - name: Checking for possible FAIL
-        run: |
-          FAILCOUNT=$(cat lintReport.txt | wc -l)
-          if [ $FAILCOUNT -gt 0]
-          then
-            echo "HAS_FAIL='true'" >> $GITHUB_ENV
-            echo "###############################"
-            echo "Listing Fails"
-            find  ${{ github.workspace }}/*/migrations -name 'V*.sql' -exec sqlfluff lint {} --dialect mysql --format=human \; | grep "==" | awk '{ print $2" "$3 }' | sed 's/\[//g' | sed 's/\]//g'
-          else
-            echo "HAS_FAIL='false'"  >> $GITHUB_ENV
-          fi
-
-          
   fix:
     needs:
-      - check-lint
+      - lint
     runs-on: self-hosted
-    if: ${{ github.env.HAS_FAIL == 'true' }}
     steps:
+      - name: Check for FAIL
+        run: |
+            if grep -q 'FAIL' lintReport.txt; then
+              echo "FAIL found in lintReport.txt. Exiting the workflow."
+              exit 1
+            else
+              echo "No FAIL found in lintReport.txt. Continuing with the workflow."
+            fi
+            
       - name: Fix SQL Files and generate report
+        if: success()
         run: |
            find ${{ github.workspace}}/*/migrations -name '*.sql' -exec sqlfluff fix {} --dialect mysql  --format=human --force \; >> lintFixReport.txt
 
