retest lint

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -43,7 +43,10 @@ jobs:
       - name: Lint SQL files and generate report
         run: |
           find ${{ github.workspace }}/*/migrations -name '*.sql' -exec sqlfluff lint {} --dialect mysql --format=human \; >> testereport.txt
-
+          if [ $? -ne 0 ]; then
+          echo "Linting failed. Exiting workflow."
+          exit 1
+          fi
 # Uncomment the following section if you want to include a "fix" job
 #   fix:
 #     needs:
